# Generated by Django 2.1.7 on 2019-03-06 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='picture',
            new_name='article',
        ),
    ]
